# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=44397

// List all to do items
GET {{host}}:{{port}}/api/todoitems/all

###

// List all incomplete to do items
GET {{host}}:{{port}}/api/todoitems

###

// Get a specific to do item
@id_to_get=3fa85f64-5717-4562-b3fc-2c963f66afa6
GET {{host}}:{{port}}/api/todoitems/{{id_to_get}}

###

// Add a new todo item
POST {{host}}:{{port}}/api/todoitems
Content-Type: application/json

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "description": "This is a to do item",
  "isCompleted": false
}

###

// Update a to do item
@id_to_update=3fa85f64-5717-4562-b3fc-2c963f66afa6
PUT {{host}}:{{port}}/api/todoitems/3fa85f64-5717-4562-b3fc-2c963f66afa6
Content-Type: application/json

{
  "id": "{{id_to_update}}",
  "description": "Updated to do item",
  "isCompleted": true
}
